version: '3'

services:


    app:
        restart: always
        build:
            context: ./source
            dockerfile: Dockerfile.app
            args:
                - BUILD_FOR=development
        env_file:
            - ./environments/base.env
            - ./environments/development.env
        volumes:
            - ./source:/usr/src/app:rw
        command: bash -c "./docker-entrypoint.sh"
        ports:
            - "80:80"


    postgres:
        build: ./postgres
        volumes:
            - ./data/database/:/var/lib/postgresql/data/:rw
