# Generated by Django 3.0.2 on 2020-01-21 10:43

import apps.tos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedTOS',
            fields=[
                ('street', models.CharField(blank=True, max_length=1024, null=True, verbose_name='street')),
                ('post_code', models.CharField(blank=True, max_length=1024, null=True, verbose_name='post code')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Entry id', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when entry was created', verbose_name='Created at')),
                ('signed_file', models.FileField(upload_to=apps.tos.models.signed_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Signed TOS entry',
                'verbose_name_plural': 'Signed TOS entries',
            },
        ),
    ]
