# Generated by Django 3.0.2 on 2020-01-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0002_auto_20200121_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signedtos',
            options={'ordering': ['created_at'], 'verbose_name': 'Signed TOS entry', 'verbose_name_plural': 'Signed TOS entries'},
        ),
        migrations.AlterField(
            model_name='signedtos',
            name='created_at',
            field=models.DateTimeField(help_text='Date and time when entry was created', verbose_name='Created at'),
        ),
    ]
