# Generated by Django 3.0.2 on 2020-01-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='post code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='street'),
        ),
    ]
